version: '3.4'

networks:
  blossomapinetwork:

services:
  postgresdb:
    container_name: app-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BlossomDb
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - blossomapinetwork

  blossomapi:
    container_name: blossom-api
    image: ${DOCKER_REGISTRY-}blossomapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - postgresdb
    environment:
      - DATABASE_URL=User ID=postgres;Password=postgres;Host=postgresdb;Port=5432;Database=BlossomDb;Pooling=true;
      - ASPNETCORE_ENVIRONMENT=ENV
    networks:
      - blossomapinetwork
volumes:
  app_data:
